site_name: Dictionarry
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline

        name: Switch to dark mode
      primary: blue
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.prune
extra_css:
  - stylesheets/table.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
