site_name: Dictionarry
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7

        name: Switch to dark mode
      primary: black
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - content.code.copy
extra_css:
  - stylesheets/table.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "Ahoy!": "index.md"
  - "Custom Formats":
      - "Audio": "Custom Formats/Audio.md"
      - "Codecs": "Custom Formats/Codecs.md"
      - "Editions": "Custom Formats/Editions.md"
      - "Extras": "Custom Formats/Extras.md"
      - "Flags": "Custom Formats/Flags.md"
      - "HDR": "Custom Formats/HDR.md"
      - "Release Groups": "Custom Formats/Release Groups.md"
      - "Resolutions": "Custom Formats/Resolutions.md"
      - "Sources": "Custom Formats/Sources.md"
  - "Profiles":
      - "Home": "Profiles/Home.md"
      - "Profile Selector": "https://selectarr.pages.dev"
      - "2160p Optimal": "Profiles/2160p Optimal.md"
      - "1080p Optimal": "Profiles/1080p Optimal.md"
      - "1080p Transparent": "Profiles/1080p Transparent.md"
      - "1080p Balanced": "Profiles/1080p Balanced.md"
      - "1080p h265 Balanced": "Profiles/1080p h265 Balanced.md"
  - "Wiki":
      - "Golden Popcorn Performance Index": "Wiki/Golden Popcorn Performance Index.md"
      - "Importing Profiles & Custom Formats": "Wiki/Importing Profiles & Custom Formats.md"
      - "Release Group Tiers": "Wiki/Release Group Tiers.md"
      - "Issues & Feedback": "Wiki/Issues & Feedback.md"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js